#!/bin/bash
set -euo pipefail

# Regenerate the vendored pure-PHP Snowball stemmers in src/Index/Snowball/.
#
# The stemmers are generated by the Snowball compiler's `-php` backend at the
# pinned commit below, then mechanically transformed for this package
# (namespace, PHP 8.1-compatible constants). Output must stay byte-identical
# to the sha256 manifest in src/Index/Snowball/PROVENANCE.md —
# SnowballProvenanceTest fails until the manifest is re-baselined, so
# regeneration is always explicit.
#
# WARNING — the pin is a mainline COMMIT, not a release tag, and that is
# deliberate: it is the exact snowball revision pagefind_stem 1.0.0 (the crate
# inside Pagefind 1.5.0's query WASM) was generated from, verified by
# byte-comparing the compiler's -rust output for all 34 algorithms plus the
# rust runtime against the crate's vendored sources. Neither adjacent tag is
# parity-correct:
#   - v3.0.0 diverges on 18 English words (internal, interval, interfered,
#     skis, ...) — it predates the english.sbl fixes the crate has.
#   - v3.1.1 diverges on da/fi/it/no (and de apostrophe words): snowball
#     3.1.x added apostrophe/elision handling Pagefind 1.5.0 does not have
#     (2,103 divergent words across the committed corpora).
# Also: the "Generated from X.sbl by Snowball <version>" header in each file
# is the compiler's own version string, not proof of the algorithm state —
# this commit self-reports "3.0.0". Trust the commit hash, never the header.
#
# Usage: ./scripts/generate-stemmers.sh
# Run manually, commit output. Not run during CI.

SNOWBALL_REPO="https://github.com/snowballstem/snowball.git"
# Mainline commit between v3.0.0 and v3.1.0: "Support -eprefix for all target
# languages". See WARNING above for why this exact revision.
SNOWBALL_COMMIT="019c1bdd5fa3925257f30b225a2c4eba49968fe8"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"
OUT_DIR="${PACKAGE_DIR}/src/Index/Snowball"

# Language code => Snowball algorithm name. This is exactly the set Pagefind
# 1.5.0 enables for these codes (pagefind_web/Cargo.toml feature map): note
# nl => dutch is the MODERN dutch algorithm, not dutch_porter.
LANGUAGES=(
    "ca:catalan:CatalanStemmer"
    "da:danish:DanishStemmer"
    "de:german:GermanStemmer"
    "en:english:EnglishStemmer"
    "es:spanish:SpanishStemmer"
    "fi:finnish:FinnishStemmer"
    "fr:french:FrenchStemmer"
    "it:italian:ItalianStemmer"
    "nl:dutch:DutchStemmer"
    "no:norwegian:NorwegianStemmer"
    "pt:portuguese:PortugueseStemmer"
    "ro:romanian:RomanianStemmer"
    "ru:russian:RussianStemmer"
    "sv:swedish:SwedishStemmer"
)

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

echo "Cloning snowball at ${SNOWBALL_COMMIT}..."
git clone --quiet "${SNOWBALL_REPO}" "${WORK_DIR}/snowball"
git -C "${WORK_DIR}/snowball" checkout --quiet "${SNOWBALL_COMMIT}"

ACTUAL_COMMIT="$(git -C "${WORK_DIR}/snowball" rev-parse HEAD)"
if [ "${ACTUAL_COMMIT}" != "${SNOWBALL_COMMIT}" ]; then
    echo "ERROR: checkout resolved to ${ACTUAL_COMMIT}, expected ${SNOWBALL_COMMIT}." >&2
    exit 1
fi

echo "Building the Snowball compiler..."
make -s -C "${WORK_DIR}/snowball" snowball >/dev/null

# Transform generated/runtime PHP for this package. Mechanical and idempotent:
#  1. Add the package namespace after the opening <?php line (the generated
#     classes are global by default, which must not leak out of the package).
#  2. Strip the type from typed class constants ("private const array A_0" is
#     PHP 8.3+ syntax; this package supports >=8.1). Value semantics are
#     unchanged — the corpus byte-parity tests validate the transformed code.
#  3. Drop the compiler's hardcoded "Snowball" class-name prefix (the -php
#     backend emits "class Snowball<name>") so class names are PSR-4-clean
#     under the Snowball namespace: EnglishStemmer, not SnowballEnglishStemmer.
transform() {
    local src="$1" dest="$2"
    awk '{ print }
         $0 == "<?php" && !done { print ""; print "namespace Tag1\\Scolta\\Index\\Snowball;"; done=1 }' "${src}" \
        | sed -E 's/^( *(public|protected|private) const) (array|int|string|float|bool) /\1 /' \
        | sed -E 's/^class Snowball([A-Za-z]+Stemmer) extends SnowballStemmer$/class \1 extends SnowballStemmer/' \
        > "${dest}"
}

mkdir -p "${OUT_DIR}"
rm -f "${OUT_DIR}"/*.php

echo "Vendoring the runtime base class..."
transform "${WORK_DIR}/snowball/php/base-stemmer.php" "${OUT_DIR}/SnowballStemmer.php"

for entry in "${LANGUAGES[@]}"; do
    algorithm="${entry#*:}"; algorithm="${algorithm%%:*}"
    class="${entry##*:}"
    echo "Generating ${class} (${algorithm})..."
    "${WORK_DIR}/snowball/snowball" \
        "${WORK_DIR}/snowball/algorithms/${algorithm}.sbl" \
        -php -n "${class}" \
        -o "${WORK_DIR}/${class}"
    transform "${WORK_DIR}/${class}.php" "${OUT_DIR}/${class}.php"
done

echo "Copying the Snowball license..."
cp "${WORK_DIR}/snowball/COPYING" "${OUT_DIR}/LICENSE"

# Guard: no post-8.1 syntax may survive the transform. Typed class constants,
# dynamic class-constant fetch (C::{$x}) and #[\Override] are 8.3+; readonly
# classes and standalone (true|false|null) types are 8.2+.
echo "Checking for post-8.1 syntax in the output..."
if grep -nE 'const +(array|int|string|float|bool) |::\{|#\[\\?Override|readonly +class|\): *(true|false|null) *\{' "${OUT_DIR}"/*.php; then
    echo "ERROR: post-8.1 syntax found in generated output (see matches above)." >&2
    exit 1
fi

echo
echo "sha256 manifest (update PROVENANCE.md if these changed):"
(cd "${OUT_DIR}" && shasum -a 256 ./*.php LICENSE | sed 's|\./||')
echo
echo "Done. Generated from snowball commit ${ACTUAL_COMMIT}."
echo "Now run the corpus parity tests: composer test -- --filter Stemmer"
